# reusable.yml
name: Common Setup
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ['test', 'lint']
        node-version: ['20']

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Or latest compatible

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Start Development Server
        run: pnpm run dev &  # Replace with your actual start command

      - name: Wait for Server to Start (using curl)
        run: |
          for i in {1..60}; do
            if curl --fail --silent http://localhost:3000 > /dev/null; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 1
            fi
          done
          if [[ $i -eq 60 ]]; then
            echo "Server did not start after 60 seconds."
            exit 1
          fi

      - name: Run Task ${{ matrix.task }}
        shell: bash
        run: |
          if [[ "${{ matrix.task }}" == "test" ]]; then
            pnpm playwright install --with-deps
            pnpm playwright test
          elif [[ "${{ matrix.task }}" == "lint" ]]; then
            pnpm run lint
          else
            echo "Unknown task: ${{ matrix.task }}"
            exit 1
          fi

      - name: Stop Development Server
        if: always()
        run: |
          if pkill -f "pnpm run dev"; then  # Try to kill the process
            echo "Server stopped."
          else
            echo "Server was not running or already stopped."
          fi