# reusable.yml
name: Common Setup
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ['test', 'lint']
        node-version: ['20']

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Task ${{ matrix.task }}
        shell: bash
        run: |
          if [[ "${{ matrix.task }}" == "test" ]]; then
            pnpm playwright install --with-deps
            pnpm playwright test
          elif [[ "${{ matrix.task }}" == "lint" ]]; then
            pnpm run lint
          else
            echo "Unknown task: ${{ matrix.task }}"
            exit 1
          fi