# test.yml
name: Playwright Tests and Linting
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality-assurance:
    uses: ./.github/workflows/reusable.yml
    permissions:
      contents: read