# test.yml
name: QA
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-and-lint:
    uses: ./.github/workflows/reusable.yml
    permissions:
      contents: read